# UCI Cervical Cancer Data

We will analyse the data


In [1]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression,LogisticRegressionCV
from sklearn.metrics import mean_squared_error, confusion_matrix, roc_curve, auc, precision_score
import matplotlib.pyplot as plt
from imblearn.under_sampling import InstanceHardnessThreshold
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB, MultinomialNB
import cPickle

In [2]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
import warnings
from sklearn.preprocessing import Imputer, scale
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)

In [3]:
df = pd.read_csv("risk_factors_cervical_cancer.csv",na_values="NaN")
df
#will work without explicitly providing NaN as na_values

Age  Number of sexual partners  First sexual intercourse  \
0     18                        4.0                      15.0   
1     15                        1.0                      14.0   
2     34                        1.0                       NaN   
3     52                        5.0                      16.0   
4     46                        3.0                      21.0   
5     42                        3.0                      23.0   
6     51                        3.0                      17.0   
7     26                        1.0                      26.0   
8     45                        1.0                      20.0   
9     44                        3.0                      15.0   
10    44                        3.0                      26.0   
11    27                        1.0                      17.0   
12    45                        4.0                      14.0   
13    44                        2.0                      25.0   
14    43                        2.0                      18.0   
15    40                        3.0                      18.0   
16    41                        4.0                      21.0   
17    43                        3.0                      15.0   
18    42                        2.0                      20.0   
19    40                        2.0                      27.0   
20    43                        2.0                      18.0   
21    41                        3.0                      17.0   
22    40                        1.0                      18.0   
23    40                        1.0                      20.0   
24    40                        3.0                      15.0   
25    44                        3.0                      19.0   
26    39                        5.0                      23.0   
27    39                        2.0                      17.0   
28    37                        3.0                      24.0   
29    37                        6.0                      26.0   
30    41                        3.0                      17.0   
31    40                        2.0                      21.0   
32    37                        3.0                      17.0   
33    37                        3.0                      15.0   
34    38                        2.0                      15.0   
35    37                        3.0                      17.0   
36    39                        2.0                      17.0   
37    37                        NaN                      18.0   
38    39                        1.0                      24.0   
39    36                        2.0                      20.0   
40    37                        NaN                      17.0   
41    37                        2.0                      18.0   
42    36                        3.0                      18.0   
43    36                        3.0                      17.0   
44    37                        3.0                      19.0   
45    36                        1.0                      17.0   
46    36                        2.0                      18.0   
47    40                        2.0                      20.0   
48    41                        2.0                      17.0   
49    37                        3.0                      18.0   
..   ...                        ...                       ...   
808   29                        NaN                      14.0   
809   29                        2.0                      13.0   
810   19                        1.0                      13.0   
811   17                        1.0                      16.0   
812   14                        5.0                      16.0   
813   20                        1.0                      17.0   
814   16                        1.0                      12.0   
815   30                        1.0                      16.0   
816   21                        2.0                      19.0   
817   29                        1.0     

In [4]:
y = df[["Hinselmann","Schiller","Citology","Biopsy"]]
#df = df.drop(["Hinselmann","Schiller","Citology","Biopsy"], axis=1)
#df
imp = Imputer(missing_values='NaN', strategy='mean', axis=0, copy=False)#toimpute along columns
df1 = imp.fit_transform(df)
df1 = pd.DataFrame(df1)
df1.columns = df.columns
df = df1
df["Biopsy"] = y["Biopsy"]
df["Hinselmann"] = y["Hinselmann"]
df["Schiller"] = y["Schiller"]
df["Citology"] = y["Citology"]
def cervical_cancer(cancer_label):
    
    hil, sch, cit, bio = cancer_label
    
    return hil+sch+cit+bio

df['cervical_cancer'] = df[['Hinselmann', 'Schiller', 'Citology','Biopsy']].apply(cervical_cancer,axis=1)
#df.cervical_cancer = df.cervical_cancer.astype(int)
df

#cancer_df_features = df.drop(["Hinselmann","Schiller","Citology","Biopsy"], axis=1)
#cancer_df_label = pd.DataFrame(data=df['Hinselmann'])

#cancer_df_label['Schiller'] = df['Schiller']
#cancer_df_label['Citology'] = df['Citology']
#cancer_df_label['Biopsy'] = df['Biopsy']

#cancer_df_label['cervical_cancer'] = cancer_df_label[['Hinselmann', 'Schiller', 'Citology','Biopsy']].apply(cervical_cancer,axis=1)
#cancer_df_label



Age  Number of sexual partners  First sexual intercourse  \
0    18.0                   4.000000                   15.0000   
1    15.0                   1.000000                   14.0000   
2    34.0                   1.000000                   16.9953   
3    52.0                   5.000000                   16.0000   
4    46.0                   3.000000                   21.0000   
5    42.0                   3.000000                   23.0000   
6    51.0                   3.000000                   17.0000   
7    26.0                   1.000000                   26.0000   
8    45.0                   1.000000                   20.0000   
9    44.0                   3.000000                   15.0000   
10   44.0                   3.000000                   26.0000   
11   27.0                   1.000000                   17.0000   
12   45.0                   4.000000                   14.0000   
13   44.0                   2.000000                   25.0000   
14   43.0                   2.000000                   18.0000   
15   40.0                   3.000000                   18.0000   
16   41.0                   4.000000                   21.0000   
17   43.0                   3.000000                   15.0000   
18   42.0                   2.000000                   20.0000   
19   40.0                   2.000000                   27.0000   
20   43.0                   2.000000                   18.0000   
21   41.0                   3.000000                   17.0000   
22   40.0                   1.000000                   18.0000   
23   40.0                   1.000000                   20.0000   
24   40.0                   3.000000                   15.0000   
25   44.0                   3.000000                   19.0000   
26   39.0                   5.000000                   23.0000   
27   39.0                   2.000000                   17.0000   
28   37.0                   3.000000                   24.0000   
29   37.0                   6.000000                   26.0000   
30   41.0                   3.000000                   17.0000   
31   40.0                   2.000000                   21.0000   
32   37.0                   3.000000                   17.0000   
33   37.0                   3.000000                   15.0000   
34   38.0                   2.000000                   15.0000   
35   37.0                   3.000000                   17.0000   
36   39.0                   2.000000                   17.0000   
37   37.0                   2.527644                   18.0000   
38   39.0                   1.000000                   24.0000   
39   36.0                   2.000000                   20.0000   
40   37.0                   2.527644                   17.0000   
41   37.0                   2.000000                   18.0000   
42   36.0                   3.000000                   18.0000   
43   36.0                   3.000000                   17.0000   
44   37.0                   3.000000                   19.0000   
45   36.0                   1.000000                   17.0000   
46   36.0                   2.000000                   18.0000   
47   40.0                   2.000000                   20.0000   
48   41.0                   2.000000                   17.0000   
49   37.0                   3.000000                   18.0000   
..    ...                        ...                       ...   
808  29.0                   2.527644                   14.0000   
809  29.0                   2.000000                   13.0000   
810  19.0                   1.000000                   13.0000   
811  17.0                   1.000000                   16.0000   
812  14.0                   5.000000                   16.0000   
813  20.0                   1.000000                   17.0000   
814  16.0                   1.000000                   12.0000   
815  30.0                   1.000000                   16.0000   
816  21.0                   2.000000          

In [5]:
X_tr, X_te = train_test_split(df, train_size=0.75)
y_tr = X_tr[["Hinselmann","Schiller","Citology","Biopsy","cervical_cancer"]]
y_te = X_te[["Hinselmann","Schiller","Citology","Biopsy","cervical_cancer"]]
X_tr = X_tr.drop(["Hinselmann","Schiller","Citology","Biopsy","cervical_cancer"], axis=1)
X_te = X_te.drop(["Hinselmann","Schiller","Citology","Biopsy","cervical_cancer"], axis=1)
print("Training Shape: " + str(X_tr.shape))
print("Testing Shape:  " + str(X_te.shape))
print("Training Shape: " + str(y_tr.shape))
print("Testing Shape:  " + str(y_te.shape))

Training Shape: (643, 32)
Testing Shape:  (215, 32)
Training Shape: (643, 5)
Testing Shape:  (215, 5)


In [6]:
y_tem = np.sum(y_te)
print("Positive test data = \n" + str(y_tem))
print("Negative test data = \n" + str(y_te.__len__() - y_tem))
y_tem = np.sum(y_tr)
print("Positive train data = \n" + str(y_tem))
print("Negative train data = \n" + str(y_tr.__len__() - y_tem))

Positive test data = 
Hinselmann          7
Schiller           14
Citology           10
Biopsy             11
cervical_cancer    42
dtype: int64
Negative test data = 
Hinselmann         208
Schiller           201
Citology           205
Biopsy             204
cervical_cancer    173
dtype: int64
Positive train data = 
Hinselmann          28
Schiller            60
Citology            34
Biopsy              44
cervical_cancer    166
dtype: int64
Negative train data = 
Hinselmann         615
Schiller           583
Citology           609
Biopsy             599
cervical_cancer    477
dtype: int64


In [7]:
#iht = InstanceHardnessThreshold(random_state=42)
#X_iht, y_iht = iht.fit_sample(X_tr, y_tr)
#y_tem = np.sum(y)
#print("Positive data = " + str(y_tem))
#print("Negative data = " + str(y_tr.__len__() - y_tem))

In [8]:
#model = LogisticRegressionCV(max_iter=35, penalty='l1', solver='liblinear')
#model = SVC(kernel="poly", degree=3)
#model = GaussianNB()
#model = MultinomialNB()
model= RandomForestClassifier(n_jobs=4, bootstrap=True, class_weight=None, criterion='gini',max_depth=None, max_features='auto', max_leaf_nodes=None,
                         min_samples_leaf=1, min_samples_split=2,min_weight_fraction_leaf=0.0, n_estimators=10, 
                         oob_score=False, random_state=None, verbose=0,warm_start=False)

model.fit(X_tr,y_tr)
#model.fit(X_iht, y_iht)
score = mean_squared_error(y_tr, np.round(model.predict(X_tr)))
"Mean Squared Error CV = " + str(score)

'Mean Squared Error CV = 0.04354587869362364'

In [9]:
print model.predict(X_te)
prob={"actual":pd.DataFrame(y_te),"prediction": pd.DataFrame(model.predict(X_te))}
prob
#prob = pd.DataFrame(cancer_df_label)
#prob[['prediction'] = model.predict(cancer_df_features)
#prob.columns = ["actual", "prediction"]
#prob

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


{'actual':      Hinselmann  Schiller  Citology  Biopsy  cervical_cancer
 389           0         0         0       0                0
 745           0         0         0       0                0
 399           0         0         0       0                0
 110           0         0         0       0                0
 583           0         0         0       0                0
 426           0         0         0       0                0
 849           0         0         0       0                0
 270           0         0         0       0                0
 668           0         1         0       0                1
 228           0         0         0       0                0
 497           0         0         0       0                0
 528           0         0         0       0                0
 4             0         0         0       0                0
 596           0         0         0       0                0
 674           0         0         0       0                

In [10]:
#result = pd.DataFrame(model.coef_[0])
#result['predictor'] = X_tr.columns
#result.columns = ["coefficient", "predictor"]
#result[result["coefficient"]!=0]

In [11]:
def generateConfusionMatrixROCandAUC(result, X, y):
    prediction= result.predict(X)
    a=[]
    #print y["cervical_cancer"]
    for i in range(len(X)):
        a.append(np.round(prediction[i][4]))
    conf_matrix = confusion_matrix(y["cervical_cancer"], a,labels=[1,0])
    print(conf_matrix)
    '''fpr, tpr, threshold = roc_curve(y, prediction[i], pos_label=1)
    roc_auc = auc(fpr, tpr)
    plt.figure()
    lw = 2
    plt.plot(fpr, tpr, color='darkorange',
             lw=lw, label='ROC curve (area = %0.2f)' % roc_auc)
    plt.plot([0, 1], [0, 1], color='navy', lw=lw, linestyle='--')
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.0])
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('Receiver operating characteristic curve')
    plt.legend(loc="lower right")
    plt.show()
    '''
generateConfusionMatrixROCandAUC(model, X_tr, y_tr)

[[ 32   3]
 [  0 560]]


In [12]:
score_te = mean_squared_error(y_te, np.round(model.predict(X_te)))
"Test Error  = " + str(score_te)

'Test Error  = 0.14511627906976746'

In [13]:
generateConfusionMatrixROCandAUC(model, X_te, y_te)

[[  0   5]
 [  1 193]]


In [14]:
results = []
np.sum(results)>=results.__len__()/2

True

In [15]:
filename = 'rand_model.sav'
cPickle.dump(model, open(filename, 'wb'))
 
# some time later...
 
 #load the model from disk
#loaded_model = cPickle.load(open(filename, 'rb'))
#result = loaded_model.score(X_te, y_te)
#print(result)
